import { LANGUAGE_CODES, type Language } from "./languages";
import type { ComparisonField } from "./extraction";
import { FIELD_LABELS } from "./fieldLabels";

const en = {
  "officialRule": "What the official rule says",
  "home": "Know what changed in your contract.",
  "intro": "Check your signed employment contract against your original job offer.",
  "start": "Check my contract",
  "upload": "Add your documents",
  "fileHelp": "Choose a JPG or PNG image for each document, up to 3 MB each.",
  "readerHelp": "Clear printed English documents can be read on your device. If OpenAI is configured, images are sent to OpenAI, with device reading as a fallback.",
  "offerImage": "Job offer image",
  "contractImage": "Contract image",
  "chooseFile": "Choose image",
  "selected": "Selected",
  "check": "Check",
  "reading": "Reading your documents",
  "sampleIntro": "Try a sample comparison without uploading images.",
  "sample": "Use sample documents",
  "examples": "Try an example",
  "salaryCase": "Salary and job title changed",
  "matchingCase": "Terms match",
  "hoursCase": "Hours and leave changed",
  "salaryDescription": "Two differences: job title and monthly salary.",
  "matchingDescription": "All listed terms match; unstated terms remain Not found.",
  "hoursDescription": "Two differences: weekly hours and annual leave.",
  "back": "Back",
  "results": "Your comparison",
  "sampleNotice": "Sample comparison. These are demonstration documents.",
  "offline": "Offline mode: reading done on this device",
  "preparedNotice": "Prepared example loaded on this device. No OCR or AI call was used.",
  "liveNotice": "Read with OpenAI. Check every value and quote against your documents.",
  "deviceNotice": "Device reading completed. Check every value and quote against your documents; OCR can make mistakes.",
  "unreadable": "No terms could be compared.",
  "unreadableHelp": "Try a clearer printed English image or use sample documents. This is not a matching-contract result.",
  "downloadOffer": "Download sample offer",
  "downloadContract": "Download sample contract",
  "generated": "Generated on",
  "differences": "{n} differences found.",
  "differentMeaning": "A term marked Different means this is different from your offer.",
  "missingMeaning": "Not found means the term was missing or could not be read in one or both documents.",
  "tapTerm": "Tap a term name to read what it means.",
  "different": "Different",
  "same": "Same",
  "notFound": "Not found",
  "promised": "What was promised",
  "written": "What is written",
  "offerSays": "Your offer says:",
  "contractSays": "Your contract says:",
  "noQuote": "No source quote available.",
  "meaning": "What this means",
  "summary": "Your summary",
  "listen": "Listen",
  "preparingAudio": "Preparing audio…",
  "localAudio": "Audio uses an installed device voice; no API calls.",
  "englishAudio": "No installed voice for this language; Listen reads the English text.",
  "noAudio": "No installed language or English voice. The written text is available.",
  "liveAudio": "Audio uses an AI voice when available, with device speech as a fallback.",
  "playAudio": "Press Play in the audio controls to listen.",
  "audioError": "Audio could not play. The written text is available.",
  "listening": "Listening with an installed device voice.",
  "rule": "Rule card",
  "help": "Where to get help",
  "routingNote": "You select the authority. TrueTerms does not determine jurisdiction or submit your summary.",
  "routingQuestion": "Which authority do you want on your summary?",
  "notSure": "Other free zone or not sure",
  "bring": "What to bring",
  "bringNote": "Documents used in this comparison. This is not an authority checklist.",
  "print": "Print or save my summary",
  "footer": "Information only, not legal advice. For help call MOHRE 80084.",
  "source": "Source: TrueTerms project rules, AGENTS.md, rule 8. No legal source supplied.",
  "draft": "Translations are drafts and are being reviewed.",
  "documents": "Documents used",
  "imageHelp": "Check the values and quotes against these images.",
  "yourOffer": "Your offer",
  "yourContract": "Your contract",
  "error": "Checking is unavailable. Try again or use sample documents.",
  "formatError": "Choose a JPG or PNG image.",
  "sizeError": "Choose an image smaller than 3 MB.",
  "retry": "Try again",
  "slow": "Reading took too long. Try again or use sample documents.",
  "offerRead": "Offer read",
  "contractRead": "Contract read",
  "comparing": "Comparing",
  "language": "Language"
};

const ur: Record<keyof typeof en, string> = {
  "officialRule": "سرکاری قاعدہ کیا کہتا ہے",
  "home": "جانیں کہ آپ کے معاہدے میں کیا بدلا ہے۔",
  "intro": "اپنے دستخط شدہ معاہدے کا اصل ملازمت کی پیشکش سے موازنہ کریں۔",
  "start": "میرا معاہدہ چیک کریں",
  "upload": "اپنی دستاویزات شامل کریں",
  "fileHelp": "ہر دستاویز کی JPG یا PNG تصویر منتخب کریں، زیادہ سے زیادہ 3 MB۔",
  "readerHelp": "صاف چھپی ہوئی انگریزی دستاویزات آپ کے آلے پر پڑھی جا سکتی ہیں۔ OpenAI دستیاب ہو تو تصاویر OpenAI کو بھیجی جاتی ہیں؛ ورنہ آلہ پڑھتا ہے۔",
  "offerImage": "ملازمت کی پیشکش کی تصویر",
  "contractImage": "معاہدے کی تصویر",
  "chooseFile": "تصویر منتخب کریں",
  "selected": "منتخب",
  "check": "چیک کریں",
  "reading": "آپ کی دستاویزات پڑھ رہے ہیں",
  "sampleIntro": "تصاویر اپ لوڈ کیے بغیر نمونہ موازنہ آزمائیں۔",
  "sample": "نمونہ دستاویزات استعمال کریں",
  "examples": "ایک مثال آزمائیں",
  "salaryCase": "تنخواہ اور عہدہ بدلے",
  "matchingCase": "شرائط یکساں ہیں",
  "hoursCase": "گھنٹے اور چھٹی بدلے",
  "salaryDescription": "دو فرق: عہدہ اور ماہانہ تنخواہ۔",
  "matchingDescription": "تمام درج شرائط یکساں ہیں؛ غیر درج شرائط نہیں ملیں۔",
  "hoursDescription": "دو فرق: ہفتہ وار گھنٹے اور سالانہ چھٹی۔",
  "back": "واپس",
  "results": "آپ کا موازنہ",
  "sampleNotice": "نمونہ موازنہ۔ یہ نمائشی دستاویزات ہیں۔",
  "offline": "آف لائن موڈ: پڑھائی اسی آلے پر ہوئی",
  "preparedNotice": "تیار مثال اسی آلے پر کھولی گئی۔ کوئی OCR یا AI کال نہیں ہوئی۔",
  "liveNotice": "OpenAI سے پڑھا گیا۔ ہر قدر اور اقتباس اصل دستاویز سے چیک کریں۔",
  "deviceNotice": "آلے کی پڑھائی مکمل ہوئی۔ ہر قدر اور اقتباس دستاویز سے چیک کریں؛ OCR غلطی کر سکتا ہے۔",
  "unreadable": "کسی شرط کا موازنہ نہیں ہو سکا۔",
  "unreadableHelp": "صاف چھپی انگریزی تصویر یا نمونہ استعمال کریں۔ یہ معاہدے کے یکساں ہونے کا نتیجہ نہیں۔",
  "downloadOffer": "نمونہ پیشکش ڈاؤن لوڈ کریں",
  "downloadContract": "نمونہ معاہدہ ڈاؤن لوڈ کریں",
  "generated": "تیار ہونے کی تاریخ",
  "differences": "{n} فرق ملے۔",
  "differentMeaning": "مختلف نشان والی شرط آپ کی پیشکش سے مختلف ہے۔",
  "missingMeaning": "نہیں ملا یعنی شرط ایک یا دونوں دستاویزات میں غائب تھی یا پڑھی نہیں جا سکی۔",
  "tapTerm": "معنی پڑھنے کے لیے شرط کے نام پر دبائیں۔",
  "different": "مختلف",
  "same": "یکساں",
  "notFound": "نہیں ملا",
  "promised": "کیا وعدہ کیا گیا",
  "written": "کیا لکھا ہے",
  "offerSays": "آپ کی پیشکش کہتی ہے:",
  "contractSays": "آپ کا معاہدہ کہتا ہے:",
  "noQuote": "اصل اقتباس دستیاب نہیں۔",
  "meaning": "اس کا مطلب",
  "summary": "آپ کا خلاصہ",
  "listen": "سنیں",
  "preparingAudio": "آڈیو تیار ہو رہا ہے…",
  "localAudio": "آڈیو آلے کی نصب آواز استعمال کرتا ہے؛ کوئی API کال نہیں۔",
  "englishAudio": "اس زبان کی آواز نصب نہیں؛ سنیں انگریزی متن پڑھتا ہے۔",
  "noAudio": "اس زبان یا انگریزی کی آواز نصب نہیں۔ تحریری متن دستیاب ہے۔",
  "liveAudio": "دستیاب ہو تو آڈیو AI آواز استعمال کرتا ہے؛ ورنہ آلے کی آواز۔",
  "playAudio": "سننے کے لیے آڈیو میں پلے دبائیں۔",
  "audioError": "آڈیو نہیں چلا۔ تحریری متن دستیاب ہے۔",
  "listening": "آلے کی نصب آواز سے سن رہے ہیں۔",
  "rule": "معلوماتی کارڈ",
  "help": "مدد کہاں ملے گی",
  "routingNote": "آپ ادارہ منتخب کرتے ہیں۔ TrueTerms دائرہ اختیار طے یا خلاصہ جمع نہیں کرتا۔",
  "routingQuestion": "خلاصے پر کون سا ادارہ چاہتے ہیں؟",
  "notSure": "دوسرا فری زون یا معلوم نہیں",
  "bring": "کیا ساتھ لائیں",
  "bringNote": "اس موازنے میں استعمال شدہ دستاویزات۔ یہ ادارے کی چیک لسٹ نہیں۔",
  "print": "میرا خلاصہ پرنٹ یا محفوظ کریں",
  "footer": "صرف معلومات، قانونی مشورہ نہیں۔ مدد کے لیے MOHRE 80084 پر کال کریں۔",
  "source": "ماخذ: TrueTerms منصوبے کے اصول، AGENTS.md، اصول 8۔ قانونی ماخذ فراہم نہیں کیا گیا۔",
  "draft": "ترجمے مسودے ہیں اور ان کا جائزہ لیا جا رہا ہے۔",
  "documents": "استعمال شدہ دستاویزات",
  "imageHelp": "قدریں اور اقتباسات ان تصاویر سے چیک کریں۔",
  "yourOffer": "آپ کی پیشکش",
  "yourContract": "آپ کا معاہدہ",
  "error": "چیک دستیاب نہیں۔ دوبارہ کوشش کریں یا نمونہ استعمال کریں۔",
  "formatError": "JPG یا PNG تصویر منتخب کریں۔",
  "sizeError": "3 MB سے چھوٹی تصویر منتخب کریں۔",
  "retry": "دوبارہ کوشش کریں",
  "slow": "پڑھنے میں زیادہ وقت لگا۔ دوبارہ کوشش کریں یا نمونہ استعمال کریں۔",
  "offerRead": "پیشکش پڑھی گئی",
  "contractRead": "معاہدہ پڑھا گیا",
  "comparing": "موازنہ ہو رہا ہے",
  "language": "زبان"
};

const hi: Record<keyof typeof en, string> = {
  "officialRule": "आधिकारिक नियम क्या कहता है",
  "home": "जानें आपके अनुबंध में क्या बदला।",
  "intro": "अपने हस्ताक्षरित अनुबंध की मूल नौकरी प्रस्ताव से तुलना करें।",
  "start": "मेरा अनुबंध जाँचें",
  "upload": "अपने दस्तावेज़ जोड़ें",
  "fileHelp": "हर दस्तावेज़ की JPG या PNG छवि चुनें, अधिकतम 3 MB।",
  "readerHelp": "स्पष्ट छपे अंग्रेज़ी दस्तावेज़ आपके उपकरण पर पढ़े जा सकते हैं। OpenAI उपलब्ध हो तो छवियाँ OpenAI को भेजी जाती हैं; उपकरण विकल्प है।",
  "offerImage": "नौकरी प्रस्ताव की छवि",
  "contractImage": "अनुबंध की छवि",
  "chooseFile": "छवि चुनें",
  "selected": "चुना गया",
  "check": "जाँचें",
  "reading": "आपके दस्तावेज़ पढ़ रहे हैं",
  "sampleIntro": "छवियाँ अपलोड किए बिना नमूना तुलना देखें।",
  "sample": "नमूना दस्तावेज़ इस्तेमाल करें",
  "examples": "एक उदाहरण आज़माएँ",
  "salaryCase": "वेतन और पद बदले",
  "matchingCase": "शर्तें समान हैं",
  "hoursCase": "घंटे और छुट्टी बदले",
  "salaryDescription": "दो अंतर: पद और मासिक वेतन।",
  "matchingDescription": "सभी लिखी शर्तें समान हैं; अनलिखी शर्तें नहीं मिलीं।",
  "hoursDescription": "दो अंतर: साप्ताहिक घंटे और सालाना छुट्टी।",
  "back": "वापस",
  "results": "आपकी तुलना",
  "sampleNotice": "नमूना तुलना। ये प्रदर्शन के दस्तावेज़ हैं।",
  "offline": "ऑफ़लाइन मोड: पढ़ना इसी उपकरण पर हुआ",
  "preparedNotice": "तैयार उदाहरण उपकरण पर खोला गया। कोई OCR या AI कॉल नहीं हुई।",
  "liveNotice": "OpenAI से पढ़ा गया। हर मान और उद्धरण मूल दस्तावेज़ से जाँचें।",
  "deviceNotice": "उपकरण पर पढ़ना पूरा हुआ। हर मान और उद्धरण जाँचें; OCR गलतियाँ कर सकता है।",
  "unreadable": "किसी शर्त की तुलना नहीं हुई।",
  "unreadableHelp": "स्पष्ट छपी अंग्रेज़ी छवि या नमूना इस्तेमाल करें। यह अनुबंध समान होने का परिणाम नहीं।",
  "downloadOffer": "नमूना प्रस्ताव डाउनलोड करें",
  "downloadContract": "नमूना अनुबंध डाउनलोड करें",
  "generated": "तैयार करने की तारीख",
  "differences": "{n} अंतर मिले।",
  "differentMeaning": "अलग चिह्न वाली शर्त आपके प्रस्ताव से अलग है।",
  "missingMeaning": "नहीं मिला का अर्थ है शर्त एक या दोनों दस्तावेज़ों में गायब थी या पढ़ी नहीं गई।",
  "tapTerm": "अर्थ पढ़ने के लिए शर्त के नाम पर दबाएँ।",
  "different": "अलग",
  "same": "समान",
  "notFound": "नहीं मिला",
  "promised": "क्या वादा किया गया",
  "written": "क्या लिखा है",
  "offerSays": "आपके प्रस्ताव में लिखा है:",
  "contractSays": "आपके अनुबंध में लिखा है:",
  "noQuote": "मूल उद्धरण उपलब्ध नहीं।",
  "meaning": "इसका अर्थ",
  "summary": "आपका सारांश",
  "listen": "सुनें",
  "preparingAudio": "ऑडियो तैयार हो रहा है…",
  "localAudio": "ऑडियो उपकरण की स्थापित आवाज़ से चलता है; कोई API कॉल नहीं।",
  "englishAudio": "इस भाषा की आवाज़ नहीं है; सुनें अंग्रेज़ी पाठ पढ़ता है।",
  "noAudio": "इस भाषा या अंग्रेज़ी की आवाज़ नहीं। लिखित पाठ उपलब्ध है।",
  "liveAudio": "उपलब्ध होने पर AI आवाज़, अन्यथा उपकरण की आवाज़।",
  "playAudio": "सुनने के लिए ऑडियो में प्ले दबाएँ।",
  "audioError": "ऑडियो नहीं चला। लिखित पाठ उपलब्ध है।",
  "listening": "उपकरण की स्थापित आवाज़ सुन रहे हैं।",
  "rule": "जानकारी कार्ड",
  "help": "मदद कहाँ मिलेगी",
  "routingNote": "आप प्राधिकरण चुनते हैं। TrueTerms अधिकार क्षेत्र तय नहीं करता और सारांश जमा नहीं करता।",
  "routingQuestion": "सारांश पर कौन सा प्राधिकरण चाहते हैं?",
  "notSure": "अन्य फ्री ज़ोन या निश्चित नहीं",
  "bring": "क्या साथ लाएँ",
  "bringNote": "इस तुलना में उपयोग किए दस्तावेज़। यह प्राधिकरण की सूची नहीं।",
  "print": "मेरा सारांश प्रिंट या सेव करें",
  "footer": "केवल जानकारी, कानूनी सलाह नहीं। सहायता के लिए MOHRE 80084 पर कॉल करें।",
  "source": "स्रोत: TrueTerms परियोजना नियम, AGENTS.md, नियम 8। कानूनी स्रोत नहीं दिया गया।",
  "draft": "अनुवाद प्रारूप हैं और समीक्षा हो रही है।",
  "documents": "इस्तेमाल किए दस्तावेज़",
  "imageHelp": "मान और उद्धरण इन छवियों से जाँचें।",
  "yourOffer": "आपका प्रस्ताव",
  "yourContract": "आपका अनुबंध",
  "error": "जाँच उपलब्ध नहीं। फिर कोशिश करें या नमूना इस्तेमाल करें।",
  "formatError": "JPG या PNG छवि चुनें।",
  "sizeError": "3 MB से छोटी छवि चुनें।",
  "retry": "फिर कोशिश करें",
  "slow": "पढ़ने में अधिक समय लगा। फिर कोशिश करें या नमूना इस्तेमाल करें।",
  "offerRead": "प्रस्ताव पढ़ा गया",
  "contractRead": "अनुबंध पढ़ा गया",
  "comparing": "तुलना हो रही है",
  "language": "भाषा"
};

const bn: Record<keyof typeof en, string> = {
  "officialRule": "সরকারি নিয়ম কী বলে",
  "home": "আপনার চুক্তিতে কী বদলেছে জানুন।",
  "intro": "স্বাক্ষরিত চুক্তির সঙ্গে মূল চাকরির প্রস্তাব তুলনা করুন।",
  "start": "আমার চুক্তি যাচাই করুন",
  "upload": "আপনার নথি যোগ করুন",
  "fileHelp": "প্রতিটি নথির JPG বা PNG ছবি বাছুন, সর্বোচ্চ 3 MB।",
  "readerHelp": "পরিষ্কার ছাপা ইংরেজি নথি আপনার যন্ত্রে পড়া যায়। OpenAI থাকলে ছবি OpenAI-তে পাঠানো হয়; যন্ত্রে পড়া বিকল্প।",
  "offerImage": "চাকরির প্রস্তাবের ছবি",
  "contractImage": "চুক্তির ছবি",
  "chooseFile": "ছবি বাছুন",
  "selected": "নির্বাচিত",
  "check": "যাচাই করুন",
  "reading": "আপনার নথি পড়া হচ্ছে",
  "sampleIntro": "ছবি আপলোড ছাড়াই নমুনা তুলনা দেখুন।",
  "sample": "নমুনা নথি ব্যবহার করুন",
  "examples": "একটি উদাহরণ দেখুন",
  "salaryCase": "বেতন ও পদ বদলেছে",
  "matchingCase": "শর্ত একই",
  "hoursCase": "ঘণ্টা ও ছুটি বদলেছে",
  "salaryDescription": "দুটি পার্থক্য: পদ ও মাসিক বেতন।",
  "matchingDescription": "সব লেখা শর্ত একই; না লেখা শর্ত পাওয়া যায়নি।",
  "hoursDescription": "দুটি পার্থক্য: সাপ্তাহিক ঘণ্টা ও বার্ষিক ছুটি।",
  "back": "ফিরুন",
  "results": "আপনার তুলনা",
  "sampleNotice": "নমুনা তুলনা। এগুলো প্রদর্শনের নথি।",
  "offline": "অফলাইন মোড: এই যন্ত্রেই পড়া হয়েছে",
  "preparedNotice": "প্রস্তুত উদাহরণ যন্ত্রে খোলা হয়েছে। কোনো OCR বা AI কল হয়নি।",
  "liveNotice": "OpenAI দিয়ে পড়া হয়েছে। প্রতিটি মান ও উদ্ধৃতি মূল নথির সঙ্গে যাচাই করুন।",
  "deviceNotice": "যন্ত্রে পড়া শেষ হয়েছে। প্রতিটি মান ও উদ্ধৃতি যাচাই করুন; OCR ভুল করতে পারে।",
  "unreadable": "কোনো শর্ত তুলনা করা যায়নি।",
  "unreadableHelp": "পরিষ্কার ছাপা ইংরেজি ছবি বা নমুনা ব্যবহার করুন। এটি চুক্তি একই থাকার ফল নয়।",
  "downloadOffer": "নমুনা প্রস্তাব ডাউনলোড করুন",
  "downloadContract": "নমুনা চুক্তি ডাউনলোড করুন",
  "generated": "তৈরির তারিখ",
  "differences": "{n}টি পার্থক্য পাওয়া গেছে।",
  "differentMeaning": "আলাদা চিহ্নিত শর্ত আপনার প্রস্তাব থেকে আলাদা।",
  "missingMeaning": "পাওয়া যায়নি অর্থ শর্ত একটি বা উভয় নথিতে অনুপস্থিত বা পড়া যায়নি।",
  "tapTerm": "অর্থ পড়তে শর্তের নামে চাপুন।",
  "different": "আলাদা",
  "same": "একই",
  "notFound": "পাওয়া যায়নি",
  "promised": "কী প্রতিশ্রুতি ছিল",
  "written": "কী লেখা আছে",
  "offerSays": "আপনার প্রস্তাবে লেখা:",
  "contractSays": "আপনার চুক্তিতে লেখা:",
  "noQuote": "মূল উদ্ধৃতি নেই।",
  "meaning": "এর অর্থ",
  "summary": "আপনার সারাংশ",
  "listen": "শুনুন",
  "preparingAudio": "অডিও তৈরি হচ্ছে…",
  "localAudio": "অডিও যন্ত্রের ইনস্টল করা কণ্ঠ ব্যবহার করে; API কল নেই।",
  "englishAudio": "এই ভাষার কণ্ঠ নেই; শুনুন ইংরেজি পাঠ পড়ে।",
  "noAudio": "এই ভাষা বা ইংরেজির কণ্ঠ নেই। লেখা উপলব্ধ।",
  "liveAudio": "থাকলে AI কণ্ঠ, নইলে যন্ত্রের কণ্ঠ।",
  "playAudio": "শুনতে অডিওতে প্লে চাপুন।",
  "audioError": "অডিও চলেনি। লেখা উপলব্ধ।",
  "listening": "যন্ত্রের ইনস্টল করা কণ্ঠে শোনা হচ্ছে।",
  "rule": "তথ্য কার্ড",
  "help": "সাহায্য কোথায় পাবেন",
  "routingNote": "আপনি কর্তৃপক্ষ বাছেন। TrueTerms এখতিয়ার নির্ধারণ বা সারাংশ জমা দেয় না।",
  "routingQuestion": "সারাংশে কোন কর্তৃপক্ষ চান?",
  "notSure": "অন্য ফ্রি জোন বা নিশ্চিত নন",
  "bring": "কী সঙ্গে আনবেন",
  "bringNote": "এই তুলনায় ব্যবহৃত নথি। এটি কর্তৃপক্ষের তালিকা নয়।",
  "print": "আমার সারাংশ ছাপুন বা সংরক্ষণ করুন",
  "footer": "শুধু তথ্য, আইনি পরামর্শ নয়। সহায়তার জন্য MOHRE 80084-তে কল করুন।",
  "source": "উৎস: TrueTerms প্রকল্পের নিয়ম, AGENTS.md, নিয়ম 8। আইনি উৎস দেওয়া হয়নি।",
  "draft": "অনুবাদ খসড়া এবং পর্যালোচনা চলছে।",
  "documents": "ব্যবহৃত নথি",
  "imageHelp": "মান ও উদ্ধৃতি এই ছবির সঙ্গে যাচাই করুন।",
  "yourOffer": "আপনার প্রস্তাব",
  "yourContract": "আপনার চুক্তি",
  "error": "যাচাই উপলব্ধ নয়। আবার চেষ্টা বা নমুনা ব্যবহার করুন।",
  "formatError": "JPG বা PNG ছবি বাছুন।",
  "sizeError": "3 MB-এর ছোট ছবি বাছুন।",
  "retry": "আবার চেষ্টা করুন",
  "slow": "পড়তে বেশি সময় লেগেছে। আবার চেষ্টা বা নমুনা ব্যবহার করুন।",
  "offerRead": "প্রস্তাব পড়া হয়েছে",
  "contractRead": "চুক্তি পড়া হয়েছে",
  "comparing": "তুলনা হচ্ছে",
  "language": "ভাষা"
};

const LABELS: Record<Language, Record<ComparisonField, string>> = {
  English: FIELD_LABELS,
  Urdu: {
    employer_name: "آجر کا نام", job_title: "ملازمت کا عہدہ", monthly_salary_aed: "ماہانہ تنخواہ (درہم)",
    allowances_aed: "الاؤنس (درہم)", work_location: "کام کی جگہ", weekly_hours: "ہفتہ وار کام کے گھنٹے",
    annual_leave_days: "سالانہ چھٹی کے دن", contract_duration: "معاہدے کی مدت", passport_clause: "پاسپورٹ کی شق",
  },
  Hindi: {
    employer_name: "नियोक्ता का नाम", job_title: "पद", monthly_salary_aed: "मासिक वेतन (AED)",
    allowances_aed: "भत्ते (AED)", work_location: "काम की जगह", weekly_hours: "साप्ताहिक काम के घंटे",
    annual_leave_days: "सालाना छुट्टी के दिन", contract_duration: "अनुबंध की अवधि", passport_clause: "पासपोर्ट की शर्त",
  },
  Bengali: {
    employer_name: "নিয়োগকর্তার নাম", job_title: "পদের নাম", monthly_salary_aed: "মাসিক বেতন (AED)",
    allowances_aed: "ভাতা (AED)", work_location: "কাজের স্থান", weekly_hours: "সাপ্তাহিক কাজের ঘণ্টা",
    annual_leave_days: "বার্ষিক ছুটির দিন", contract_duration: "চুক্তির মেয়াদ", passport_clause: "পাসপোর্টের শর্ত",
  },
};

export function getStrings(language: Language) { return { en, ur, hi, bn }[LANGUAGE_CODES[language]]; }
export function getFieldLabels(language: Language) { return LABELS[language]; }
export function translateMessage(message: string, language: Language): string {
 const t=getStrings(language);
 if (!message) return "";
 const original = Object.entries(en).find(([, value]) => value === message);
 if (original) return t[original[0] as keyof typeof en];
 if (message.startsWith("Device reader found")) return language === "English" ? message : t.deviceNotice;
 if (message.startsWith("Prepared example")) return t.preparedNotice;
 if (message.startsWith("Read with OpenAI")) return t.liveNotice;
 if (message.startsWith("No readable text") || message.startsWith("The photos contained")) return t.unreadable + " " + t.unreadableHelp;
 if (message.startsWith("Reading") || message.startsWith("Loading") || message.startsWith("Checking which")) return t.reading;
 if (message.startsWith("No installed") && (message.includes("Listening") || message.includes("Listen"))) return t.englishAudio;
 if (message.startsWith("No installed")) return t.noAudio;
 if (message.includes("audio controls")) return t.playAudio;
 if (message.toLowerCase().includes("audio could not")) return t.audioError;
 if (message.startsWith("Listening")) return t.listening;
 if (message.includes("took too long")) return t.slow;
 return t.error;
}
